import type { WorkItem } from "./types";

export const work: WorkItem[] = [
  {
    slug: "classified-platform",
    title: { en: "Classified marketplace", fr: "Marketplace d’annonces" },
    client: { en: "Confidential — Gulf region", fr: "Confidentiel — région du Golfe" },
    sector: { en: "Marketplace", fr: "Marketplace" },
    summary: {
      en: "A listings platform with moderation, wallets, and a staff console that could survive real volume.",
      fr: "Une plateforme d’annonces avec modération, wallets, et une console capable d’encaisser un vrai volume.",
    },
    challenge: {
      en: "The first version looked like a product and behaved like a folder of scripts. We rebuilt the listing lifecycle, payments-adjacent flows, and the admin as the actual workplace.",
      fr: "La première version ressemblait à un produit et se comportait comme un dossier de scripts. Nous avons repris le cycle de vie des annonces, les flux autour du paiement, et l’admin comme vrai lieu de travail.",
    },
    outcome: {
      en: "A stack the client’s team can extend: web, mobile-ready APIs, and an admin that no longer needs a developer for every takedown.",
      fr: "Une stack que l’équipe cliente peut prolonger : web, APIs prêtes pour le mobile, admin qui n’exige plus un développeur pour chaque retrait.",
    },
    stack: ["React Native", "Node.js", "PostgreSQL"],
    seoTitle: { en: "Case study — classified marketplace", fr: "Étude de cas — marketplace d’annonces" },
    seoDescription: {
      en: "How Station Eight Labs approached a classified marketplace: listings, moderation, and an ops console.",
      fr: "Comment Station Eight Labs a abordé une marketplace d’annonces : listings, modération et console ops.",
    },
  },
  {
    slug: "clinic-ops",
    title: { en: "Clinic operations", fr: "Exploitation de clinique" },
    client: { en: "Confidential — independent clinic", fr: "Confidentiel — clinique indépendante" },
    sector: { en: "Healthcare", fr: "Santé" },
    summary: {
      en: "Appointments, reminders, and a front-desk console that replaced a wall of notebooks.",
      fr: "Rendez-vous, rappels, et une console d’accueil qui a remplacé un mur de carnets.",
    },
    challenge: {
      en: "The clinic did not need a hospital EHR. It needed intake, no-show reduction, and a staff tool that a receptionist would actually open.",
      fr: "La clinique n’avait pas besoin d’un DPI hospitalier. Elle avait besoin d’admission, de moins d’absences, et d’un outil qu’une réceptionniste ouvre vraiment.",
    },
    outcome: {
      en: "A first version in weeks, not a two-year transformation programme. Structured so a packaged product can follow.",
      fr: "Une première version en semaines, pas un programme de transformation de deux ans. Structuré pour qu’un produit packagé puisse suivre.",
    },
    stack: ["Next.js", "PostgreSQL"],
    seoTitle: { en: "Case study — clinic operations software", fr: "Étude de cas — logiciel d’exploitation clinique" },
    seoDescription: {
      en: "A focused clinic operations build: booking, reminders, and staff tools from Station Eight Labs.",
      fr: "Un projet ciblé d’exploitation de clinique : réservation, rappels et outils équipes par Station Eight Labs.",
    },
  },
  {
    slug: "1finance",
    title: { en: "1Finance — financial platform", fr: "1Finance — plateforme financière" },
    client: { en: "1Finance", fr: "1Finance" },
    sector: { en: "Fintech", fr: "Fintech" },
    role: { en: "Full Stack Developer · team of 6 · Oct 2022 – Present", fr: "Développeur full stack · équipe de 6 · oct. 2022 – présent" },
    isTeamExperience: true,
    summary: { en: "Financial-management backend services handling payments, credit-data, and banking workflows.", fr: "Services backend de gestion financière pour les paiements, les données de crédit et les flux bancaires." },
    challenge: { en: "Transaction status, reconciliation, and secure handling of sensitive financial and credit data needed to hold up under real banking integrations, not a demo flow.", fr: "Le statut des transactions, la réconciliation et le traitement sécurisé des données financières et de crédit devaient tenir face à de vraies intégrations bancaires, pas une démo." },
    outcome: { en: "Node.js REST services with serverless AWS Lambda for isolated background processing, plus a reusable Selenium/Page-Object-Model testing framework that improved regression coverage.", fr: "Services REST Node.js avec AWS Lambda serverless pour le traitement isolé en arrière-plan, et un framework de tests Selenium/Page Object Model réutilisable, améliorant la couverture de régression." },
    stack: ["Node.js", "TypeScript", "MySQL", "PostgreSQL", "AWS Lambda", "Razorpay"],
    seoTitle: { en: "1Finance — financial platform — Station Eight Labs team experience", fr: "1Finance — plateforme financière — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "Financial-management backend services handling payments, credit-data, and banking workflows. Delivered by our founding engineers before Station Eight Labs.", fr: "Services backend de gestion financière pour les paiements, les données de crédit et les flux bancaires. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "ruloans-crm",
    title: { en: "RuLoans CRM — loan processing platform", fr: "RuLoans CRM — plateforme de traitement de prêts" },
    client: { en: "RuLoans CRM", fr: "RuLoans CRM" },
    sector: { en: "Fintech / CRM", fr: "Fintech / CRM" },
    role: { en: "Full Stack Developer · team of 14 · Oct 2022 – Present", fr: "Développeur full stack · équipe de 14 · oct. 2022 – présent" },
    isTeamExperience: true,
    summary: { en: "Scalable CRM and loan-processing microservices for a lending operations platform.", fr: "Microservices CRM et de traitement de prêts, scalables, pour une plateforme d'opérations de crédit." },
    challenge: { en: "Multi-database persistence across MySQL and PostgreSQL needed access-control lists and role-based authorization to keep loan operations secure, on infrastructure the team managed directly.", fr: "La persistance multi-base entre MySQL et PostgreSQL exigeait des listes de contrôle d'accès et une autorisation par rôles pour sécuriser les opérations de prêt, sur une infrastructure gérée directement par l'équipe." },
    outcome: { en: "Node.js and Python microservices in production, backed by CI/CD and Selenium/Page-Object-Model automation for continuous validation.", fr: "Microservices Node.js et Python en production, avec CI/CD et automatisation Selenium/Page Object Model pour une validation continue." },
    stack: ["Node.js", "Python", "MySQL", "PostgreSQL", "Redis", "Docker", "Nginx", "AWS"],
    seoTitle: { en: "RuLoans CRM — loan processing platform — Station Eight Labs team experience", fr: "RuLoans CRM — plateforme de traitement de prêts — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "Scalable CRM and loan-processing microservices for a lending operations platform. Delivered by our founding engineers before Station Eight Labs.", fr: "Microservices CRM et de traitement de prêts, scalables, pour une plateforme d'opérations de crédit. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "brandaf",
    title: { en: "Brandaf — data integration & automation", fr: "Brandaf — intégration de données et automatisation" },
    client: { en: "Brandaf", fr: "Brandaf" },
    sector: { en: "Data Integration", fr: "Intégration de données" },
    role: { en: "Full Stack Developer · team of 8 · Jan 2022 – Oct 2022", fr: "Développeur full stack · équipe de 8 · jan. 2022 – oct. 2022" },
    isTeamExperience: true,
    summary: { en: "Integration and automation services running across three Node.js servers for a data-integration business.", fr: "Services d'intégration et d'automatisation sur trois serveurs Node.js pour une activité d'intégration de données." },
    challenge: { en: "Inbound Gmail/Outlook webhooks and scheduled processing had to stay reliable across multiple concurrent project workloads.", fr: "Les webhooks entrants Gmail/Outlook et le traitement planifié devaient rester fiables sur plusieurs charges de projet concurrentes." },
    outcome: { en: "A Python analytical service plus data-driven, parallel Selenium test execution that made release testing repeatable.", fr: "Un service analytique Python et des tests Selenium parallèles pilotés par les données, rendant les tests de mise en production reproductibles." },
    stack: ["Node.js", "Python", "MongoDB", "MySQL", "Selenium"],
    seoTitle: { en: "Brandaf — data integration & automation — Station Eight Labs team experience", fr: "Brandaf — intégration de données et automatisation — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "Integration and automation services running across three Node.js servers for a data-integration business. Delivered by our founding engineers before Station Eight Labs.", fr: "Services d'intégration et d'automatisation sur trois serveurs Node.js pour une activité d'intégration de données. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "flyout",
    title: { en: "Flyout — enterprise CRM integration", fr: "Flyout — intégration CRM d'entreprise" },
    client: { en: "Flyout", fr: "Flyout" },
    sector: { en: "CRM / Enterprise Integration", fr: "CRM / intégration d'entreprise" },
    role: { en: "Full Stack Developer · team of 12 · Sep 2021 – Dec 2021", fr: "Développeur full stack · équipe de 12 · sept. 2021 – déc. 2021" },
    isTeamExperience: true,
    summary: { en: "API-driven enterprise integrations connecting an AWS Marketplace CRM product with Salesforce and HubSpot.", fr: "Intégrations d'entreprise pilotées par API reliant un produit CRM AWS Marketplace à Salesforce et HubSpot." },
    challenge: { en: "Long-running integration work needed to be decoupled from interactive requests, with authorization and logging consistent across a mixed Node.js/Python service layer.", fr: "Le travail d'intégration long devait être découplé des requêtes interactives, avec une autorisation et une journalisation cohérentes sur une couche de services Node.js/Python mixte." },
    outcome: { en: "AWS SQS-backed background processing, centralized logging, and manual Selenium tests converted into automated smoke and regression suites.", fr: "Traitement en arrière-plan sur AWS SQS, journalisation centralisée, et tests Selenium manuels convertis en suites automatisées de smoke et de régression." },
    stack: ["Node.js", "Python", "Docker", "AWS SQS", "Salesforce", "HubSpot"],
    seoTitle: { en: "Flyout — enterprise CRM integration — Station Eight Labs team experience", fr: "Flyout — intégration CRM d'entreprise — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "API-driven enterprise integrations connecting an AWS Marketplace CRM product with Salesforce and HubSpot. Delivered by our founding engineers before Station Eight Labs.", fr: "Intégrations d'entreprise pilotées par API reliant un produit CRM AWS Marketplace à Salesforce et HubSpot. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "playback-health",
    title: { en: "Playback Health — care communication platform", fr: "Playback Health — plateforme de communication santé" },
    client: { en: "Playback Health", fr: "Playback Health" },
    sector: { en: "Healthcare", fr: "Santé" },
    role: { en: "Architect + Developer · team of 9 · Jan 2021 – Aug 2021", fr: "Architecte + développeur · équipe de 9 · jan. 2021 – août 2021" },
    isTeamExperience: true,
    summary: { en: "Centralized backend and API design for a healthcare communication platform spanning React, Node.js, and Java microservices.", fr: "Backend centralisé et conception d'API pour une plateforme de communication santé mêlant React, Node.js et microservices Java." },
    challenge: { en: "Defining clean API boundaries between a React front end, a GraphQL/Express Node.js backend, and existing Java microservices, while wiring in payments and communications providers.", fr: "Définir des frontières d'API propres entre un front React, un backend Node.js GraphQL/Express et des microservices Java existants, tout en intégrant paiements et prestataires de communication." },
    outcome: { en: "A GraphQL Apollo + Express backend in TypeScript, with Stripe/Xendit payments and Twilio/Microsoft Teams communication integrated through Python services.", fr: "Un backend GraphQL Apollo + Express en TypeScript, avec paiements Stripe/Xendit et communication Twilio/Microsoft Teams intégrés via des services Python." },
    stack: ["Node.js", "TypeScript", "Apollo GraphQL", "React", "Java", "Stripe", "Twilio"],
    seoTitle: { en: "Playback Health — care communication platform — Station Eight Labs team experience", fr: "Playback Health — plateforme de communication santé — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "Centralized backend and API design for a healthcare communication platform spanning React, Node.js, and Java microservices. Delivered by our founding engineers before Station Eight Labs.", fr: "Backend centralisé et conception d'API pour une plateforme de communication santé mêlant React, Node.js et microservices Java. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "msg91",
    title: { en: "MSG91 — bulk messaging platform", fr: "MSG91 — plateforme de messagerie en masse" },
    client: { en: "MSG91", fr: "MSG91" },
    sector: { en: "Messaging", fr: "Messagerie" },
    role: { en: "Architect + Developer · team of 20 · Feb 2020 – Dec 2020", fr: "Architecte + développeur · équipe de 20 · fév. 2020 – déc. 2020" },
    isTeamExperience: true,
    summary: { en: "Bulk-messaging and internal communication platform built for throughput at scale.", fr: "Plateforme de messagerie en masse et de communication interne conçue pour un débit à grande échelle." },
    challenge: { en: "Concurrent, high-volume messaging workloads needed multithreaded processing and a data layer able to handle both messaging-scale and relational data.", fr: "Des charges de messagerie concurrentes et à fort volume exigeaient un traitement multithread et une couche de données capable de gérer à la fois l'échelle messagerie et les données relationnelles." },
    outcome: { en: "A Django/Flask platform on Cassandra and MariaDB, with Rest Assured/TestNG and Selenium automation covering reliability and throughput.", fr: "Une plateforme Django/Flask sur Cassandra et MariaDB, avec automatisation Rest Assured/TestNG et Selenium couvrant fiabilité et débit." },
    stack: ["Python", "Django", "Flask", "Cassandra", "MariaDB"],
    seoTitle: { en: "MSG91 — bulk messaging platform — Station Eight Labs team experience", fr: "MSG91 — plateforme de messagerie en masse — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "Bulk-messaging and internal communication platform built for throughput at scale. Delivered by our founding engineers before Station Eight Labs.", fr: "Plateforme de messagerie en masse et de communication interne conçue pour un débit à grande échelle. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "grorapid",
    title: { en: "Grorapid — email delivery automation", fr: "Grorapid — automatisation de la livraison e-mail" },
    client: { en: "Grorapid", fr: "Grorapid" },
    sector: { en: "Email / Automation", fr: "E-mail / automatisation" },
    role: { en: "Full Stack Developer · team of 5", fr: "Développeur full stack · équipe de 5" },
    isTeamExperience: true,
    summary: { en: "Automated email-delivery infrastructure for a marketing-operations product.", fr: "Infrastructure de livraison d'e-mails automatisée pour un produit marketing operations." },
    challenge: { en: "Asynchronous email processing needed to be separated from interactive requests, with domain-level deliverability configured correctly at scale.", fr: "Le traitement asynchrone des e-mails devait être séparé des requêtes interactives, avec une délivrabilité configurée correctement au niveau du domaine, à grande échelle." },
    outcome: { en: "Node.js/Django services with Redis-backed workflow management, cron scheduling, and a deployed SMTP/AWS SES delivery pipeline.", fr: "Services Node.js/Django avec gestion de flux sur Redis, planification cron, et un pipeline de livraison SMTP/AWS SES déployé." },
    stack: ["Node.js", "Django", "Redis", "AWS SES", "SMTP"],
    seoTitle: { en: "Grorapid — email delivery automation — Station Eight Labs team experience", fr: "Grorapid — automatisation de la livraison e-mail — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "Automated email-delivery infrastructure for a marketing-operations product. Delivered by our founding engineers before Station Eight Labs.", fr: "Infrastructure de livraison d'e-mails automatisée pour un produit marketing operations. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "simple-chime",
    title: { en: "Simple Chime — healthcare communication", fr: "Simple Chime — communication santé" },
    client: { en: "Simple Chime", fr: "Simple Chime" },
    sector: { en: "Healthcare", fr: "Santé" },
    role: { en: "Full Stack Developer", fr: "Développeur full stack" },
    isTeamExperience: true,
    summary: { en: "Secure patient-provider messaging and appointment scheduling platform.", fr: "Plateforme sécurisée de messagerie patient-soignant et de prise de rendez-vous." },
    challenge: { en: "Notification delivery and background scheduling had to stay reliable across web and mobile clients handling sensitive healthcare communication.", fr: "La livraison des notifications et la planification en arrière-plan devaient rester fiables sur des clients web et mobile traitant une communication de santé sensible." },
    outcome: { en: "REST APIs backed by relational databases and cloud infrastructure, with authentication, logging, and CI/CD supporting production operation.", fr: "Des API REST adossées à des bases relationnelles et une infrastructure cloud, avec authentification, journalisation et CI/CD en production." },
    stack: ["Node.js", "Python", "React", "REST APIs"],
    seoTitle: { en: "Simple Chime — healthcare communication — Station Eight Labs team experience", fr: "Simple Chime — communication santé — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "Secure patient-provider messaging and appointment scheduling platform. Delivered by our founding engineers before Station Eight Labs.", fr: "Plateforme sécurisée de messagerie patient-soignant et de prise de rendez-vous. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "woolf",
    title: { en: "Woolf — education platform", fr: "Woolf — plateforme éducative" },
    client: { en: "Woolf", fr: "Woolf" },
    sector: { en: "Education", fr: "Éducation" },
    role: { en: "Full Stack Developer", fr: "Développeur full stack" },
    isTeamExperience: true,
    summary: { en: "Core web application workflows for an education-focused digital platform.", fr: "Flux applicatifs web principaux pour une plateforme numérique orientée éducation." },
    challenge: { en: "User management and data-driven services needed a maintainable API and database layer that could support iterative product delivery.", fr: "La gestion des utilisateurs et les services pilotés par la donnée nécessitaient une couche API et base de données maintenable, capable de suivre une livraison produit itérative." },
    outcome: { en: "REST APIs with a React front end, PostgreSQL/MySQL, and Redis caching, with authentication and authorization built in.", fr: "Des API REST avec un front React, PostgreSQL/MySQL et un cache Redis, authentification et autorisation intégrées." },
    stack: ["Node.js", "Python", "React", "PostgreSQL", "Redis"],
    seoTitle: { en: "Woolf — education platform — Station Eight Labs team experience", fr: "Woolf — plateforme éducative — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "Core web application workflows for an education-focused digital platform. Delivered by our founding engineers before Station Eight Labs.", fr: "Flux applicatifs web principaux pour une plateforme numérique orientée éducation. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "gavazo",
    title: { en: "Gavazo — international money transfer app", fr: "Gavazo — app de transfert d'argent international" },
    client: { en: "Gavazo", fr: "Gavazo" },
    sector: { en: "Fintech / Mobile", fr: "Fintech / mobile" },
    role: { en: "Full Stack + Mobile Developer", fr: "Développeur full stack + mobile" },
    isTeamExperience: true,
    summary: { en: "Mobile app comparing international money-transfer rates, fees, and speed across providers.", fr: "Application mobile comparant taux, frais et rapidité de transfert d'argent international entre prestataires." },
    challenge: { en: "Financial data needed to stay fresh and accurate across providers, with secure account handling and clear error/retry states for failed transfers.", fr: "Les données financières devaient rester fraîches et exactes entre prestataires, avec une gestion sécurisée des comptes et des états d'erreur/nouvelle tentative clairs." },
    outcome: { en: "A mobile client integrated with cloud-hosted backend services, deployed and tested with production-grade practices.", fr: "Un client mobile intégré à des services backend hébergés dans le cloud, déployé et testé selon des pratiques de niveau production." },
    stack: ["React Native", "Node.js", "Python", "AWS"],
    seoTitle: { en: "Gavazo — international money transfer app — Station Eight Labs team experience", fr: "Gavazo — app de transfert d'argent international — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "Mobile app comparing international money-transfer rates, fees, and speed across providers. Delivered by our founding engineers before Station Eight Labs.", fr: "Application mobile comparant taux, frais et rapidité de transfert d'argent international entre prestataires. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "giv",
    title: { en: "Giv — caregiver management platform", fr: "Giv — plateforme de gestion des aidants" },
    client: { en: "Giv", fr: "Giv" },
    sector: { en: "Healthcare / Mobile", fr: "Santé / mobile" },
    role: { en: "Full Stack + Mobile Developer", fr: "Développeur full stack + mobile" },
    isTeamExperience: true,
    summary: { en: "Caregiver management platform covering scheduling, EVV, notes, reminders, and timesheets.", fr: "Plateforme de gestion des aidants couvrant planning, EVV, notes, rappels et feuilles de temps." },
    challenge: { en: "Scheduling state had to stay synchronized and operational data secure across role-aware caregiver, client, and admin workflows.", fr: "L'état du planning devait rester synchronisé et les données opérationnelles sécurisées, à travers des flux aidant, client et administration sensibles aux rôles." },
    outcome: { en: "React Native mobile experiences backed by Node.js/Python REST APIs, PostgreSQL/MySQL, and Redis caching, in active use by caregiver teams.", fr: "Des expériences mobiles React Native adossées à des API REST Node.js/Python, PostgreSQL/MySQL et un cache Redis, utilisées activement par des équipes d'aidants." },
    stack: ["React Native", "Node.js", "Python", "PostgreSQL", "Redis"],
    seoTitle: { en: "Giv — caregiver management platform — Station Eight Labs team experience", fr: "Giv — plateforme de gestion des aidants — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "Caregiver management platform covering scheduling, EVV, notes, reminders, and timesheets. Delivered by our founding engineers before Station Eight Labs.", fr: "Plateforme de gestion des aidants couvrant planning, EVV, notes, rappels et feuilles de temps. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "sprynt",
    title: { en: "Sprynt — local talent marketplace", fr: "Sprynt — marketplace de talents locaux" },
    client: { en: "Sprynt", fr: "Sprynt" },
    sector: { en: "Marketplace / Mobile", fr: "Marketplace / mobile" },
    role: { en: "Full Stack + Mobile Developer", fr: "Développeur full stack + mobile" },
    isTeamExperience: true,
    summary: { en: "Mobile marketplace connecting local talent with customers for on-demand tasks and gigs.", fr: "Marketplace mobile mettant en relation des talents locaux et des clients pour des tâches et missions à la demande." },
    challenge: { en: "Location-aware discovery, job requests, and in-app communication needed to stay synchronized between mobile clients and backend in real time.", fr: "La découverte géolocalisée, les demandes de mission et la communication in-app devaient rester synchronisées en temps réel entre les clients mobiles et le backend." },
    outcome: { en: "Role-based marketplace workflows with asynchronous notifications across React Native and a Node.js/Python backend.", fr: "Des flux de marketplace basés sur les rôles, avec notifications asynchrones, sur React Native et un backend Node.js/Python." },
    stack: ["React Native", "Node.js", "Python", "Redis"],
    seoTitle: { en: "Sprynt — local talent marketplace — Station Eight Labs team experience", fr: "Sprynt — marketplace de talents locaux — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "Mobile marketplace connecting local talent with customers for on-demand tasks and gigs. Delivered by our founding engineers before Station Eight Labs.", fr: "Marketplace mobile mettant en relation des talents locaux et des clients pour des tâches et missions à la demande. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "lets-go",
    title: { en: "Let's Go — school transportation platform", fr: "Let's Go — plateforme de transport scolaire" },
    client: { en: "Let's Go", fr: "Let's Go" },
    sector: { en: "Mobility", fr: "Mobilité" },
    role: { en: "Full Stack + Mobile Developer", fr: "Développeur full stack + mobile" },
    isTeamExperience: true,
    summary: { en: "School-transportation app with live tracking and verified-driver safety workflows.", fr: "Application de transport scolaire avec suivi en direct et vérification des chauffeurs pour la sécurité." },
    challenge: { en: "Stateful trip workflows spanning students, parents, drivers, and operations needed secure role-based access in a reliability-sensitive, safety-critical product.", fr: "Des flux de trajet à état, impliquant élèves, parents, chauffeurs et opérations, exigeaient un accès sécurisé par rôle dans un produit critique pour la sécurité." },
    outcome: { en: "A mobile application with live location/tracking services, background notifications, and CI/CD supporting a safety-first mobility product.", fr: "Une application mobile avec suivi de localisation en direct, notifications en arrière-plan et CI/CD, au service d'un produit de mobilité axé sécurité." },
    stack: ["React Native", "Node.js", "Python", "PostgreSQL", "Redis"],
    seoTitle: { en: "Let's Go — school transportation platform — Station Eight Labs team experience", fr: "Let's Go — plateforme de transport scolaire — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "School-transportation app with live tracking and verified-driver safety workflows. Delivered by our founding engineers before Station Eight Labs.", fr: "Application de transport scolaire avec suivi en direct et vérification des chauffeurs pour la sécurité. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "platform-risk-management",
    title: { en: "Platform Risk Management — enterprise risk platform", fr: "Platform Risk Management — plateforme de risque d'entreprise" },
    client: { en: "Platform Risk Management", fr: "Platform Risk Management" },
    sector: { en: "Enterprise Risk", fr: "Risque d'entreprise" },
    role: { en: "Architect + Developer", fr: "Architecte + développeur" },
    isTeamExperience: true,
    summary: { en: "Enterprise risk-management workflows covering controls, assessments, and operational reporting.", fr: "Flux de gestion des risques d'entreprise couvrant contrôles, évaluations et reporting opérationnel." },
    challenge: { en: "Compliance-sensitive workflows needed role-based authorization and audit-friendly data handling across AWS, Azure, and GCP services.", fr: "Des flux sensibles à la conformité exigeaient une autorisation par rôle et un traitement des données prêt pour l'audit, sur des services AWS, Azure et GCP." },
    outcome: { en: "A TypeScript/Node.js/Python platform with observability and traceable, scalable integration boundaries across enterprise systems.", fr: "Une plateforme TypeScript/Node.js/Python avec observabilité et des frontières d'intégration traçables et scalables entre systèmes d'entreprise." },
    stack: ["Node.js", "Python", "TypeScript", "PostgreSQL", "Docker"],
    seoTitle: { en: "Platform Risk Management — enterprise risk platform — Station Eight Labs team experience", fr: "Platform Risk Management — plateforme de risque d'entreprise — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "Enterprise risk-management workflows covering controls, assessments, and operational reporting. Delivered by our founding engineers before Station Eight Labs.", fr: "Flux de gestion des risques d'entreprise couvrant contrôles, évaluations et reporting opérationnel. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "ai-apps",
    title: { en: "AI Apps — LLM application features", fr: "AI Apps — fonctionnalités applicatives LLM" },
    client: { en: "AI Apps", fr: "AI Apps" },
    sector: { en: "AI / LLM", fr: "IA / LLM" },
    role: { en: "Architect + Developer", fr: "Architecte + développeur" },
    isTeamExperience: true,
    summary: { en: "AI-enabled application features built across multiple LLM providers with structured prompt/context pipelines.", fr: "Des fonctionnalités applicatives dotées d'IA, construites sur plusieurs fournisseurs de LLM avec des pipelines de prompt/contexte structurés." },
    challenge: { en: "LLM responses needed application-side validation connecting them to deterministic product logic, with retrieval, caching, and async processing for production use.", fr: "Les réponses des LLM nécessitaient une validation côté application les reliant à une logique produit déterministe, avec récupération, cache et traitement asynchrone pour la production." },
    outcome: { en: "Production AI features across GPT-4/GPT-3, Gemini, Claude, and Llama, with vector/retrieval patterns on PostgreSQL and Redis.", fr: "Des fonctionnalités d'IA en production sur GPT-4/GPT-3, Gemini, Claude et Llama, avec des patterns vectoriels/de récupération sur PostgreSQL et Redis." },
    stack: ["Python", "Node.js", "TypeScript", "PostgreSQL", "Redis"],
    seoTitle: { en: "AI Apps — LLM application features — Station Eight Labs team experience", fr: "AI Apps — fonctionnalités applicatives LLM — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "AI-enabled application features built across multiple LLM providers with structured prompt/context pipelines. Delivered by our founding engineers before Station Eight Labs.", fr: "Des fonctionnalités applicatives dotées d'IA, construites sur plusieurs fournisseurs de LLM avec des pipelines de prompt/contexte structurés. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "iti",
    title: { en: "ITI — enterprise business application", fr: "ITI — application métier d'entreprise" },
    client: { en: "ITI", fr: "ITI" },
    sector: { en: "Enterprise", fr: "Entreprise" },
    role: { en: "Full Stack Developer", fr: "Développeur full stack" },
    isTeamExperience: true,
    summary: { en: "API-driven business workflows and data-management features for an enterprise application.", fr: "Des flux métier et des fonctionnalités de gestion de données pilotés par API pour une application d'entreprise." },
    challenge: { en: "Authentication, integration handling, and automated testing had to come together for reliable, repeatable releases.", fr: "Authentification, gestion des intégrations et tests automatisés devaient converger pour des mises en production fiables et reproductibles." },
    outcome: { en: "A Node.js/Python service layer with logging and deployment automation improving long-term maintainability.", fr: "Une couche de services Node.js/Python avec journalisation et automatisation du déploiement, améliorant la maintenabilité long terme." },
    stack: ["Node.js", "Python", "TypeScript", "PostgreSQL"],
    seoTitle: { en: "ITI — enterprise business application — Station Eight Labs team experience", fr: "ITI — application métier d'entreprise — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "API-driven business workflows and data-management features for an enterprise application. Delivered by our founding engineers before Station Eight Labs.", fr: "Des flux métier et des fonctionnalités de gestion de données pilotés par API pour une application d'entreprise. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "lab-wizard",
    title: { en: "Lab Wizard — laboratory management system", fr: "Lab Wizard — système de gestion de laboratoire" },
    client: { en: "Lab Wizard", fr: "Lab Wizard" },
    sector: { en: "Laboratory / LIMS", fr: "Laboratoire / LIMS" },
    role: { en: "Full Stack Developer", fr: "Développeur full stack" },
    isTeamExperience: true,
    summary: { en: "Laboratory/process-management system centered on traceability, scheduling, and reporting.", fr: "Système de gestion de laboratoire/process centré sur la traçabilité, la planification et le reporting." },
    challenge: { en: "Audit-friendly, structured process data needed reliable integration between the UI and backend for regulated lab and manufacturing workflows.", fr: "Des données de process structurées et prêtes pour l'audit exigeaient une intégration fiable entre l'interface et le backend, pour des flux de laboratoire et de fabrication réglementés." },
    outcome: { en: "A Node.js/Python/React system with role-aware access, logging, and automated deployment for production use.", fr: "Un système Node.js/Python/React avec accès sensible aux rôles, journalisation et déploiement automatisé pour la production." },
    stack: ["Node.js", "Python", "React", "PostgreSQL"],
    seoTitle: { en: "Lab Wizard — laboratory management system — Station Eight Labs team experience", fr: "Lab Wizard — système de gestion de laboratoire — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "Laboratory/process-management system centered on traceability, scheduling, and reporting. Delivered by our founding engineers before Station Eight Labs.", fr: "Système de gestion de laboratoire/process centré sur la traçabilité, la planification et le reporting. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "dksh-malaysia-vietnam",
    title: { en: "DKSH Malaysia + Vietnam — enterprise IT", fr: "DKSH Malaisie + Vietnam — IT d'entreprise" },
    client: { en: "DKSH Malaysia + Vietnam", fr: "DKSH Malaysia + Vietnam" },
    sector: { en: "Enterprise / Digital & IT", fr: "Entreprise / digital & IT" },
    role: { en: "Full Stack Developer", fr: "Développeur full stack" },
    isTeamExperience: true,
    summary: { en: "Enterprise digital and IT initiatives supporting business operations across Malaysia and Vietnam.", fr: "Initiatives digitales et IT d'entreprise au service des opérations en Malaisie et au Vietnam." },
    challenge: { en: "Services had to integrate cleanly with SAP and Salesforce while deploying across AWS, Azure, and GCP for a multi-country enterprise.", fr: "Les services devaient s'intégrer proprement avec SAP et Salesforce, tout en étant déployés sur AWS, Azure et GCP pour une entreprise multi-pays." },
    outcome: { en: "Cross-cutting delivery across web, mobile, API, and testing concerns, aligned with enterprise integration requirements.", fr: "Une livraison transverse sur le web, le mobile, l'API et les tests, alignée sur les exigences d'intégration de l'entreprise." },
    stack: ["Node.js", "Python", "TypeScript", "SAP", "Salesforce"],
    seoTitle: { en: "DKSH Malaysia + Vietnam — enterprise IT — Station Eight Labs team experience", fr: "DKSH Malaisie + Vietnam — IT d'entreprise — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "Enterprise digital and IT initiatives supporting business operations across Malaysia and Vietnam. Delivered by our founding engineers before Station Eight Labs.", fr: "Initiatives digitales et IT d'entreprise au service des opérations en Malaisie et au Vietnam. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "skout-ai",
    title: { en: "Skout AI — AI-powered GTM platform", fr: "Skout AI — plateforme GTM propulsée par l'IA" },
    client: { en: "Skout AI", fr: "Skout AI" },
    sector: { en: "AI Sales Intelligence", fr: "Intelligence commerciale IA" },
    role: { en: "Architect + Developer", fr: "Architecte + développeur" },
    isTeamExperience: true,
    summary: { en: "AI-powered go-to-market platform combining prospecting, enrichment, outreach, and CRM-connected sales intelligence.", fr: "Plateforme go-to-market propulsée par l'IA combinant prospection, enrichissement, outreach et intelligence commerciale connectée au CRM." },
    challenge: { en: "AI features needed structured recommendations and CRM-connected actions while keeping deterministic business logic separate from LLM orchestration.", fr: "Les fonctionnalités IA devaient produire des recommandations structurées et des actions connectées au CRM, tout en séparant la logique métier déterministe de l'orchestration LLM." },
    outcome: { en: "Retrieval, caching, async processing, and observability built for data-intensive AI workloads at production scale.", fr: "Récupération, cache, traitement asynchrone et observabilité conçus pour des charges IA riches en données, à l'échelle production." },
    stack: ["Node.js", "Python", "TypeScript", "PostgreSQL", "Redis"],
    seoTitle: { en: "Skout AI — AI-powered GTM platform — Station Eight Labs team experience", fr: "Skout AI — plateforme GTM propulsée par l'IA — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "AI-powered go-to-market platform combining prospecting, enrichment, outreach, and CRM-connected sales intelligence. Delivered by our founding engineers before Station Eight Labs.", fr: "Plateforme go-to-market propulsée par l'IA combinant prospection, enrichissement, outreach et intelligence commerciale connectée au CRM. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "staryo",
    title: { en: "Staryo — real-time creator platform", fr: "Staryo — plateforme créateurs en temps réel" },
    client: { en: "Staryo", fr: "Staryo" },
    sector: { en: "Social / Real-Time Mobile", fr: "Social / mobile temps réel" },
    role: { en: "Architect + Developer", fr: "Architecte + développeur" },
    isTeamExperience: true,
    summary: { en: "Social/creator mobile platform with real-time messaging, voice, 1:1 video calls, and gamified engagement.", fr: "Plateforme mobile sociale/créateurs avec messagerie temps réel, voix, appels vidéo 1:1 et engagement gamifié." },
    challenge: { en: "Real-time state synchronization and scalable API design were core to an interactive mobile workload with streaks and task-based engagement.", fr: "La synchronisation d'état en temps réel et une conception d'API scalable étaient au cœur d'une charge mobile interactive avec séries et engagement par tâches." },
    outcome: { en: "A React Native platform with caching, background processing, and containerized deployment supporting real-time features.", fr: "Une plateforme React Native avec cache, traitement en arrière-plan et déploiement conteneurisé, au service de fonctionnalités temps réel." },
    stack: ["React Native", "Node.js", "TypeScript", "Redis", "Docker"],
    seoTitle: { en: "Staryo — real-time creator platform — Station Eight Labs team experience", fr: "Staryo — plateforme créateurs en temps réel — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "Social/creator mobile platform with real-time messaging, voice, 1:1 video calls, and gamified engagement. Delivered by our founding engineers before Station Eight Labs.", fr: "Plateforme mobile sociale/créateurs avec messagerie temps réel, voix, appels vidéo 1:1 et engagement gamifié. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "deal-radar",
    title: { en: "Deal Radar — AI sales risk intelligence", fr: "Deal Radar — intelligence IA sur le risque commercial" },
    client: { en: "Deal Radar", fr: "Deal Radar" },
    sector: { en: "AI Sales Intelligence", fr: "Intelligence commerciale IA" },
    role: { en: "Architect + Developer", fr: "Architecte + développeur" },
    isTeamExperience: true,
    summary: { en: "AI-assisted sales intelligence connecting sales-call context with CRM opportunity data to surface deal risk.", fr: "Intelligence commerciale assistée par IA reliant le contexte des appels de vente aux données d'opportunité CRM pour révéler le risque." },
    challenge: { en: "Ingestion, contextual retrieval, and structured LLM analysis needed to run as asynchronous stages with cost- and latency-aware model usage.", fr: "Ingestion, récupération contextuelle et analyse LLM structurée devaient s'exécuter en étapes asynchrones, avec un usage des modèles maîtrisé en coût et en latence." },
    outcome: { en: "Prompt/response validation and retries built into a production-reliable pipeline surfacing actionable deal alerts.", fr: "Validation des prompts/réponses et nouvelles tentatives intégrées à un pipeline fiable en production, faisant remonter des alertes exploitables." },
    stack: ["Python", "Node.js", "TypeScript", "PostgreSQL", "Redis"],
    seoTitle: { en: "Deal Radar — AI sales risk intelligence — Station Eight Labs team experience", fr: "Deal Radar — intelligence IA sur le risque commercial — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "AI-assisted sales intelligence connecting sales-call context with CRM opportunity data to surface deal risk. Delivered by our founding engineers before Station Eight Labs.", fr: "Intelligence commerciale assistée par IA reliant le contexte des appels de vente aux données d'opportunité CRM pour révéler le risque. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "easy-bus",
    title: { en: "Easy Bus — bus booking platform", fr: "Easy Bus — plateforme de réservation de bus" },
    client: { en: "Easy Bus", fr: "Easy Bus" },
    sector: { en: "Travel / Booking", fr: "Voyage / réservation" },
    role: { en: "Full Stack Developer", fr: "Développeur full stack" },
    isTeamExperience: true,
    summary: { en: "Online bus-booking platform covering e-ticketing, payments, cancellations, and rescheduling.", fr: "Plateforme de réservation de bus en ligne couvrant e-billetterie, paiements, annulations et changements de date." },
    challenge: { en: "Payment, ticket, and cancellation workflows needed transactional consistency across a high-volume booking-state system.", fr: "Les flux de paiement, de billet et d'annulation exigeaient une cohérence transactionnelle sur un système d'état de réservation à fort volume." },
    outcome: { en: "Integrated payment gateways, notifications, and background jobs supporting reliable booking operations.", fr: "Passerelles de paiement, notifications et tâches en arrière-plan intégrées, au service d'opérations de réservation fiables." },
    stack: ["React", "Node.js", "Python", "PostgreSQL", "Redis"],
    seoTitle: { en: "Easy Bus — bus booking platform — Station Eight Labs team experience", fr: "Easy Bus — plateforme de réservation de bus — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "Online bus-booking platform covering e-ticketing, payments, cancellations, and rescheduling. Delivered by our founding engineers before Station Eight Labs.", fr: "Plateforme de réservation de bus en ligne couvrant e-billetterie, paiements, annulations et changements de date. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "miss-gavazo",
    title: { en: "Miss Gavazo — financial AI agent", fr: "Miss Gavazo — agent IA financier" },
    client: { en: "Miss Gavazo", fr: "Miss Gavazo" },
    sector: { en: "AI Agent", fr: "Agent IA" },
    role: { en: "AI Agent Developer", fr: "Développeur d'agents IA" },
    isTeamExperience: true,
    summary: { en: "LLM-driven AI-agent workflow helping users navigate financial and product information for the Gavazo product.", fr: "Flux d'agent IA piloté par LLM, aidant les utilisateurs à naviguer dans l'information financière et produit de Gavazo." },
    challenge: { en: "Agent interactions needed context retrieval and tool/API calls validated and kept separate from raw model output, with human-review boundaries for safety.", fr: "Les interactions de l'agent nécessitaient une récupération de contexte et des appels d'outils/API validés, séparés de la sortie brute du modèle, avec des limites de revue humaine pour la sécurité." },
    outcome: { en: "A production AI agent with prompt engineering, response validation, and logging for safer real-world use.", fr: "Un agent IA en production avec ingénierie de prompt, validation des réponses et journalisation, pour un usage réel plus sûr." },
    stack: ["Python", "Node.js", "TypeScript", "PostgreSQL", "Redis"],
    seoTitle: { en: "Miss Gavazo — financial AI agent — Station Eight Labs team experience", fr: "Miss Gavazo — agent IA financier — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "LLM-driven AI-agent workflow helping users navigate financial and product information for the Gavazo product. Delivered by our founding engineers before Station Eight Labs.", fr: "Flux d'agent IA piloté par LLM, aidant les utilisateurs à naviguer dans l'information financière et produit de Gavazo. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
  {
    slug: "dexterai",
    title: { en: "DexterAI — GTM AI copilot", fr: "DexterAI — copilote IA go-to-market" },
    client: { en: "DexterAI", fr: "DexterAI" },
    sector: { en: "AI Agent / GTM Copilot", fr: "Agent IA / copilote GTM" },
    role: { en: "AI Agent Developer", fr: "Développeur d'agents IA" },
    isTeamExperience: true,
    summary: { en: "AI-agent copilot for research, contextual analysis, content generation, and sales/deal execution support.", fr: "Copilote agent IA pour la recherche, l'analyse contextuelle, la génération de contenu et le support à l'exécution commerciale." },
    challenge: { en: "Agentic workflows needed to retrieve business context and reason over structured data while keeping cost and reliability under control.", fr: "Les flux agentiques devaient récupérer le contexte métier et raisonner sur des données structurées, tout en maîtrisant coût et fiabilité." },
    outcome: { en: "Structured outputs, context grounding, retries, and provider/model selection built for reliability and cost control, using AI-assisted development tooling in the build.", fr: "Sorties structurées, ancrage contextuel, nouvelles tentatives et sélection de fournisseur/modèle, conçus pour la fiabilité et la maîtrise des coûts, avec des outils de développement assistés par IA." },
    stack: ["Python", "Node.js", "TypeScript", "PostgreSQL", "Redis"],
    seoTitle: { en: "DexterAI — GTM AI copilot — Station Eight Labs team experience", fr: "DexterAI — copilote IA go-to-market — expérience de l'équipe Station Eight Labs" },
    seoDescription: { en: "AI-agent copilot for research, contextual analysis, content generation, and sales/deal execution support. Delivered by our founding engineers before Station Eight Labs.", fr: "Copilote agent IA pour la recherche, l'analyse contextuelle, la génération de contenu et le support à l'exécution commerciale. Livré par nos ingénieurs fondateurs avant Station Eight Labs." },
  },
];
