import {
  Atom,
  Binary,
  Building2,
  Cloud,
  ConciergeBell,
  Cpu,
  Database,
  Dumbbell,
  Factory,
  Globe,
  GraduationCap,
  HeartPulse,
  KeyRound,
  Landmark,
  Layers,
  LayoutDashboard,
  MapPinned,
  NotebookPen,
  Orbit,
  PanelsTopLeft,
  Rocket,
  School,
  Scissors,
  Search,
  Server,
  Shield,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Stethoscope,
  Store,
  Truck,
  UtensilsCrossed,
  Workflow,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  globe: Globe,
  smartphone: Smartphone,
  cpu: Cpu,
  sparkles: Sparkles,
  server: Server,
  rocket: Rocket,
  "layout-dashboard": LayoutDashboard,
  search: Search,
  wrench: Wrench,
  "heart-pulse": HeartPulse,
  "graduation-cap": GraduationCap,
  landmark: Landmark,
  truck: Truck,
  "shopping-bag": ShoppingBag,
  "building-2": Building2,
  "concierge-bell": ConciergeBell,
  factory: Factory,
  shield: Shield,
  orbit: Orbit,
  stethoscope: Stethoscope,
  school: School,
  dumbbell: Dumbbell,
  scissors: Scissors,
  "utensils-crossed": UtensilsCrossed,
  store: Store,
  "key-round": KeyRound,
  "map-pinned": MapPinned,
  "panels-top-left": PanelsTopLeft,
  atom: Atom,
  binary: Binary,
  layers: Layers,
  database: Database,
  cloud: Cloud,
  workflow: Workflow,
  "notebook-pen": NotebookPen,
};

export function CatalogIcon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Icon = icons[name] ?? Globe;
  return <Icon className={className} aria-hidden />;
}
